# Generated by Django 4.2.7 on 2025-02-13 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0005_entityprocessus'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('type_value', models.CharField(default='organigramme', max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_column='creation_date', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='modification_date', default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_org', to='client.client')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_orga', to='entity.entity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organigrammes.organigram')),
            ],
        ),
    ]
